### ISSUE TITLE
Testruns/jobs can get "stuck" in Jenkins by not always aborting/exiting when a server returns an HTTP 500 error/status code

### ISSUE THREAD

**Issue by stephendonner** [mozilla/pytest-mozwebqa#134]
(I'm not completely sure this is a pytest-mozwebqa issue, but if someone can investigate, that'd be great!)

Occasionally, we see servers returning a 500 -- even less often, but it still happens, the job in Jenkins gets stuck, due to:
```
[gw5] Python 2.7.5 (default, Mar  9 2014, 22:15:05)  -- [GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)]
11:51:11 INTERNALERROR> Traceback (most recent call last):
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/main.py", line 79, in wrap_session
11:51:11 INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 441, in __call__
11:51:11 INTERNALERROR>     return self._docall(methods, kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 452, in _docall
11:51:11 INTERNALERROR>     res = mc.execute()
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 370, in execute
11:51:11 INTERNALERROR>     res = method(**kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/pytest_mozwebqa/pytest_mozwebqa.py", line 48, in pytest_sessionstart
11:51:11 INTERNALERROR> Traceback (most recent call last):
11:51:11 INTERNALERROR>     assert r.status_code in (200, 401), 'Base URL did not return status code 200 or 401. (URL: %s, Response: %s)' % (session.config.option.base_url, r.status_code)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/main.py", line 79, in wrap_session
11:51:11 INTERNALERROR> AssertionError: Base URL did not return status code 200 or 401. (URL: https://addons.allizom.org, Response: 500)
11:51:11 INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 441, in __call__
11:51:11 INTERNALERROR>     return self._docall(methods, kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 452, in _docall
11:51:11 INTERNALERROR>     res = mc.execute()
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 370, in execute
11:51:11 INTERNALERROR>     res = method(**kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/pytest_mozwebqa/pytest_mozwebqa.py", line 48, in pytest_sessionstart
11:51:11 INTERNALERROR>     assert r.status_code in (200, 401), 'Base URL did not return status code 200 or 401. (URL: %s, Response: %s)' % (session.config.option.base_url, r.status_code)
11:51:11 INTERNALERROR> AssertionError: Base URL did not return status code 200 or 401. (URL: https://addons.allizom.org, Response: 500)
11:51:11 INTERNALERROR> Traceback (most recent call last):
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/main.py", line 79, in wrap_session
11:51:11 INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 441, in __call__
11:51:11 INTERNALERROR>     return self._docall(methods, kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 452, in _docall
11:51:11 INTERNALERROR>     res = mc.execute()
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/_pytest/core.py", line 370, in execute
11:51:11 INTERNALERROR>     res = method(**kwargs)
11:51:11 INTERNALERROR>   File "/Users/Shared/Jenkins/Home/jobs/amo.stage.saucelabs/workspace/.env/lib/python2.7/site-packages/pytest_mozwebqa/pytest_mozwebqa.py", line 48, in pytest_sessionstart
11:51:11 INTERNALERROR>     assert r.status_code in (200, 401), 'Base URL did not return status code 200 or 401. (URL: %s, Response: %s)' % (session.config.option.base_url, r.status_code)
11:51:11 INTERNALERROR> AssertionError: Base URL did not return status code 200 or 401. (URL: https://addons.allizom.org, Response: 500)
11:51:11 [gw5] node down: Not properly terminated
11:51:11 [gw8] node down: Not properly terminated
11:51:11 [gw0] node down: Not properly terminated
```
The [gwX] part makes me think this might be related to pytest-dist, though I'm not sure.

I can see us doing a couple of things differently:
1) fail fast, fail hard (just abort the test-suite/run)
2) keep retrying until we get a 200 OK

Here's a full pastebin of the run:

http://pastebin.com/74L8bAeH

**Comment by allankilpatrick** [comment]
@davehunt 
I'm seeing this issue alot 
```
07:44:08 Xvfb stopping
07:44:08 
07:44:08 [gw0] node down: Not properly terminated
07:44:08 [gw0] FAILED XXX
07:44:08 Replacing crashed slave gw0
07:44:08 
[gw25] linux2 Python 2.7.6 cwd: /var/lib/jenkins/workspace/XXXX
07:44:08 make: *** [test] Terminated
07:44:08 INTERNALERROR> Traceback (most recent call last):
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/_pytest/main.py", line 92, in wrap_session
07:44:08 INTERNALERROR>     config.hook.pytest_sessionstart(session=session)
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
07:44:08 INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
07:44:08 INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
07:44:08 INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
07:44:08 INTERNALERROR>     res = hook_impl.function(*args)
07:44:08 INTERNALERROR>   File "<remote exec>", line 34, in pytest_sessionstart
07:44:08 INTERNALERROR>   File "<remote exec>", line 25, in sendevent
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 717, in send
07:44:08 INTERNALERROR>     self.gateway._send(Message.CHANNEL_DATA, self.id, dumps_internal(item))
07:44:08 INTERNALERROR>   File "/var/lib/jenkins/shiningpanda/jobs/ed446a20/virtualenvs/d41d8cd9/local/lib/python2.7/site-packages/execnet/gateway_base.py", line 990, in _send
07:44:08 INTERNALERROR>     raise IOError("cannot send (already closed?)")
07:44:08 INTERNALERROR> IOError: cannot send (already closed
```

`plugins: rerunfailures-0.5, timeout-1.0.0, xdist-1.14`
`py.test -v -n=auto -k  tests/ --junitxml=results.xml --reruns=3 --timeout=200`

**Comment by davehunt** [comment]
I would not recommend using pytest-timeout with pytest-xdist > 1.10 as we often saw issues such as https://bitbucket.org/pytest-dev/pytest-timeout/issues/8/internalerror-valueerror-signal-only-works. Also, this project is no longer maintained. I would recommend switching to pytest-selenium, and also it's worth updating your version of pytest-rerunfailures. If you still see issues after these changes please raise a new issue and I will try to help you.
