### ISSUE TITLE
Remove mozwebqa 

### ISSUE THREAD

**Issue by msilesgap** [mozilla/pytest-mozwebqa#140]
Hi guys, I think I have downloaded this code before, and now when I tried to run my code using pytest I'm getting some errors related to the base url and browser... I just wan to run my unitest.... I deleted the mozwebqa folder, an now I'm getting 

py.test --junitxml results.xml tests/APITests.py
Traceback (most recent call last):
  File "/usr/local/bin/py.test", line 9, in <module>
    load_entry_point('pytest==2.6.4', 'console_scripts', 'py.test')()
  File "/Library/Python/2.7/site-packages/_pytest/config.py", line 32, in main
    config = _prepareconfig(args, plugins)
  File "/Library/Python/2.7/site-packages/_pytest/config.py", line 85, in _prepareconfig
    pluginmanager=pluginmanager, args=args)
  File "/Library/Python/2.7/site-packages/_pytest/core.py", line 413, in __call__
    return self._docall(methods, kwargs)
  File "/Library/Python/2.7/site-packages/_pytest/core.py", line 424, in _docall
    res = mc.execute()
  File "/Library/Python/2.7/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/Library/Python/2.7/site-packages/_pytest/helpconfig.py", line 27, in pytest_cmdline_parse
    config = __multicall__.execute()
  File "/Library/Python/2.7/site-packages/_pytest/core.py", line 315, in execute
    res = method(**kwargs)
  File "/Library/Python/2.7/site-packages/_pytest/config.py", line 636, in pytest_cmdline_parse
    self.parse(args)
  File "/Library/Python/2.7/site-packages/_pytest/config.py", line 747, in parse
    self._preparse(args)
  File "/Library/Python/2.7/site-packages/_pytest/config.py", line 714, in _preparse
    self.pluginmanager.consider_setuptools_entrypoints()
  File "/Library/Python/2.7/site-packages/_pytest/core.py", line 179, in consider_setuptools_entrypoints
    plugin = ep.load()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources.py", line 2108, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
ImportError: No module named mozwebqa.mozwebqa

**Comment by davehunt** [comment]
Check if you have `pytest-mozwebqa` still installed by using the `pip freeze` command to output the list of installed packages. If it's listed, use `pip uninstall pytest-mozwebqa`. If you're using your default site packages then you may need to use `sudo` to uninstall the package. Please reopen this issue with the output from the above suggestions if this is still a problem.

**Comment by msilesgap** [comment]
Thanks Dave, now it is working as expected.
